FROM python:3-alpine
ADD . /api
WORKDIR /api # You will need this if you need PostgreSQL, otherwise just skip this
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev libffi-dev
RUN pip install -r requirements.txtEXPOSE 8000CMD ["./manage.py", "runserver"]